bot:
  token: "${BOT_TOKEN}"
  name: generator_bot
dropbox:
  folder: "${DROPBOX_FOLDER}"
  dataFolder: "${DROPBOX_DATA_FOLDER}"
  appKey: "${DROPBOX_APP_KEY}"
  appSecret:  "${DROPBOX_APP_SECRET}"
server:
  port: 8080
